### ISSUE TITLE
check spell miss and typos

### ISSUE THREAD

**Issue by takasehideki** [rclex/rclex_examples#19]
refer:
https://github.com/rclex/rclex/pull/217

**Comment by s-hosoai** [comment]
本プロジェクトでcodespell -S deps . を確認しましたが、特にスペルミスはありませんでした。
mix rclex.gen.msgのテンプレートにTypoがあるようなのでそちらを直した方がいいですね。
またチェックに伴いmix.lockをアップデートしました。

**Comment by takasehideki** [comment]
@s-hosoai あざっす！
そっちの spell miss はそっちで pull request なりよろっす〜

**Comment by s-hosoai** [comment]
こちら勘違いでした。（古い生成コードでチェックしてました）
すでにrclex/rclex#217で修正されておりました。
